# Generated by Django 4.2.5 on 2023-10-03 14:10

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "pretixbase",
            "0245_discount_benefit_products",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EsnAccountsTeamAssignmentRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("esn_section", models.CharField(max_length=100)),
                (
                    "local_roles",
                    multiselectfield.db.fields.MultiSelectField(max_length=300),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pretixbase.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team assignment rule",
            },
        ),
    ]
